import type { SpotifySkillConfig } from "../config";
import { interpretPrompt } from "../ai/interpret-prompt";
import {
  relatedTrackHasRealArtist,
  reviewAndRepairSelection,
} from "../domain/review-selection";
import { buildSearchQueries, selectTracks } from "../domain/select-tracks";
import {
  dedupeCandidates,
  normalizeText,
  totalDurationMs,
  uniqueStrings,
} from "../domain/filters";
import { createPlaylistWithTracks } from "../spotify/playlists";
import {
  fetchArtistTrackCandidates,
  fetchGenreSimilarArtistCandidates,
  fetchRecommendationTrackCandidates,
  resolveRequestedArtists,
  resolveSimilarArtists,
  searchTrackCandidates,
} from "../spotify/search";
import { getAuthorizedSpotifyClient } from "../spotify/auth";
import type { PlaylistGenerationResult } from "../types";
import type { PromptSpec } from "../domain/prompt-spec";

function toTitleCase(value: string): string {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function buildPlaylistName(spec: PromptSpec): string {
  if (spec.rawPrompt.toLowerCase().includes("playlist called")) {
    return spec.playlistNameHint;
  }

  const leadingTerms = uniqueStrings([
    ...spec.artists,
    ...spec.styles,
    ...spec.activities,
    ...spec.genres,
    ...spec.languages,
  ])
    .slice(0, 4)
    .map(toTitleCase);

  if (leadingTerms.length === 0) {
    return "Prompt Playlist";
  }

  return `${leadingTerms.join(" ")} Mix`;
}

function buildPlaylistDescription(spec: PromptSpec): string {
  const cleanTag = spec.allowExplicit ? "explicit-allowed" : "clean-only";
  const artistTag = spec.artists.length > 0 ? ` Artists: ${spec.artists.join(", ")}.` : "";
  const description = `Generated by spotify-playlist-skill (${cleanTag}).${artistTag} Prompt: ${spec.rawPrompt}`;

  return description.slice(0, 300);
}

export function composeSelectionWithSimilarArtistShare(
  spec: PromptSpec,
  candidates: PlaylistGenerationResult["selectedTracks"],
  alreadySelected: PlaylistGenerationResult["selectedTracks"],
): PlaylistGenerationResult["selectedTracks"] {
  if (
    !spec.includeSimilarArtists ||
    spec.artists.length === 0 ||
    spec.requestedArtistTargetShare === undefined
  ) {
    return alreadySelected;
  }

  const requestedTargetCount = Math.max(
    1,
    Math.round(spec.targetTrackCount * spec.requestedArtistTargetShare),
  );
  const relatedTargetCount = Math.max(0, spec.targetTrackCount - requestedTargetCount);
  const requestedCandidates = candidates.filter(
    (candidate) => candidate.seedArtistKind !== "related",
  );
  const relatedCandidates = candidates.filter(
    (candidate) => candidate.seedArtistKind === "related",
  );

  const requestedSelection = selectTracks(
    {
      ...spec,
      targetTrackCount: requestedTargetCount,
      includeSimilarArtists: false,
      includeOnlyRequestedArtists: false,
      requestedArtistTargetShare: undefined,
    },
    requestedCandidates,
  ).tracks;

  // When building the related pool we drop the `artists` constraint so related tracks
  // aren't forced to match the primary artist list.
  const relatedSelection = selectTracks(
    {
      ...spec,
      artists: [],
      targetTrackCount: relatedTargetCount,
      strictArtistMatch: false,
      includeOnlyRequestedArtists: false,
      includeSimilarArtists: false,
      requestedArtistTargetShare: undefined,
    },
    relatedCandidates,
  ).tracks;

  // Dedup across the two sub-pools to collapse any track that snuck into both.
  const combinedSelection = dedupeCandidates([...requestedSelection, ...relatedSelection]);

  if (combinedSelection.length >= spec.targetTrackCount) {
    return combinedSelection.slice(0, spec.targetTrackCount);
  }

  const usedUris = new Set(combinedSelection.map((candidate) => candidate.uri));

  // If one of the sub-pools fell short of its quota, top it up from the SAME sub-pool.
  // We explicitly do NOT fall back to the general `candidates` pool because it contains
  // `queryCandidates` without a seedArtistKind, which are dominated by collabs/features
  // between primary + similar artists from the big text-search query. Pulling from that
  // pool would effectively turn the "similar artist" share into a features-only share.
  const topUpFrom = (pool: PlaylistGenerationResult["selectedTracks"]): void => {
    for (const candidate of pool) {
      if (combinedSelection.length >= spec.targetTrackCount) {
        return;
      }

      if (usedUris.has(candidate.uri)) {
        continue;
      }

      combinedSelection.push(candidate);
      usedUris.add(candidate.uri);
    }
  };

  const requestedShortage = Math.max(0, requestedTargetCount - requestedSelection.length);
  const relatedShortage = Math.max(0, relatedTargetCount - relatedSelection.length);

  // Top up in order of where the gap was. This preserves the share intent: if related
  // was short we try to close that gap with more related candidates before stealing
  // requested slots, and vice versa.
  if (relatedShortage >= requestedShortage) {
    topUpFrom(relatedCandidates);
    topUpFrom(requestedCandidates);
  } else {
    topUpFrom(requestedCandidates);
    topUpFrom(relatedCandidates);
  }

  return combinedSelection.slice(0, spec.targetTrackCount);
}

/** Cap on how many AI-proposed similar artists we actually query Spotify for. */
const MAX_SIMILAR_ARTISTS_TO_RESOLVE = 8;

/**
 * Build a set of normalized genre tags that characterize the primary `artists` + user-supplied
 * genres, used to gate resolved similar artists so ambiguous names ("Derek") don't get
 * matched to unrelated English-language artists.
 */
function buildExpectedGenreSet(
  primaryArtists: ReadonlyArray<{ genres: string[] }>,
  userGenres: string[],
): Set<string> {
  const combined = [
    ...primaryArtists.flatMap((artist) => artist.genres ?? []),
    ...userGenres,
  ]
    .map((value) => normalizeText(value))
    .filter(Boolean);

  return new Set(combined);
}

/** Simple overlap check: at least one token from the expected set appears in the genres. */
function artistMatchesExpectedScene(
  genres: string[],
  expected: Set<string>,
): boolean {
  if (expected.size === 0) {
    return true;
  }

  const normalized = genres.map((value) => normalizeText(value)).filter(Boolean);

  // Spotify started returning empty genres for many artists in 2024. If we have no genre
  // signal to compare against, trust the AI (or caller) that proposed the name rather
  // than dropping a perfectly valid similar artist.
  if (normalized.length === 0) {
    return true;
  }

  return normalized.some((genre) => {
    for (const expectedGenre of expected) {
      if (!expectedGenre) {
        continue;
      }

      if (
        genre === expectedGenre ||
        genre.includes(expectedGenre) ||
        expectedGenre.includes(genre)
      ) {
        return true;
      }
    }

    return false;
  });
}

/**
 * Resolve AI-proposed similar artist names against the real Spotify catalog.
 * These are kept as non-requested seeds so their tracks stay in the "related" bucket.
 * We cap the list to avoid hammering Spotify with many parallel artist searches, and
 * drop resolved matches whose Spotify genres don't overlap with the primary scene.
 */
async function resolveSimilarArtistNames(
  spotifyApi: Awaited<ReturnType<typeof getAuthorizedSpotifyClient>>,
  names: string[],
  excludedArtistIds: Set<string>,
  expectedGenres: Set<string>,
): Promise<Awaited<ReturnType<typeof resolveRequestedArtists>>> {
  if (names.length === 0) {
    return [];
  }

  const limitedNames = names.slice(0, MAX_SIMILAR_ARTISTS_TO_RESOLVE);
  const resolved = await resolveRequestedArtists(spotifyApi, limitedNames);

  return resolved
    .filter((artist) => !excludedArtistIds.has(artist.spotifyArtistId))
    .filter((artist) => artistMatchesExpectedScene(artist.genres, expectedGenres))
    .map((artist) => ({ ...artist, isRequested: false }));
}

export async function generatePlaylistFromPrompt(
  prompt: string,
  config: SpotifySkillConfig,
): Promise<PlaylistGenerationResult> {
  const promptSpec = await interpretPrompt(prompt, config);
  const queries = buildSearchQueries(promptSpec);
  const spotifyApi = await getAuthorizedSpotifyClient(config);
  const resolvedArtists =
    promptSpec.artists.length > 0
      ? await resolveRequestedArtists(spotifyApi, promptSpec.artists)
      : [];
  const requestedArtistIds = new Set(resolvedArtists.map((artist) => artist.spotifyArtistId));
  // Prefer AI-provided similar artist names (Spotify's related-artists endpoint was
  // deprecated in late 2024 and now returns 404). Fall back to the legacy related
  // endpoint for backward compatibility when the AI didn't provide any.
  const expectedGenres = buildExpectedGenreSet(resolvedArtists, promptSpec.genres);
  const aiNamedSimilarArtists =
    promptSpec.includeSimilarArtists && promptSpec.similarArtists.length > 0
      ? await resolveSimilarArtistNames(
          spotifyApi,
          promptSpec.similarArtists,
          requestedArtistIds,
          expectedGenres,
        )
      : [];
  const legacySimilarArtists =
    promptSpec.includeSimilarArtists &&
    resolvedArtists.length > 0 &&
    aiNamedSimilarArtists.length === 0
      ? await resolveSimilarArtists(spotifyApi, resolvedArtists, {
          preferredGenres: promptSpec.genres,
          limit: Math.max(2, promptSpec.artists.length * 2),
        })
      : [];
  const similarArtists = [...aiNamedSimilarArtists, ...legacySimilarArtists];
  const seededArtists = [...resolvedArtists, ...similarArtists];
  const [artistCandidates, queryCandidates, recommendationCandidates, genreFallbackCandidates] = await Promise.all([
    seededArtists.length > 0
      ? fetchArtistTrackCandidates(spotifyApi, seededArtists, {
          market: config.spotifyDefaultMarket,
          includeRecentTracks: promptSpec.preferRecentTracks,
        })
      : Promise.resolve([]),
    searchTrackCandidates(spotifyApi, queries, {
      market: config.spotifyDefaultMarket,
      limitPerQuery: Math.max(10, Math.ceil(promptSpec.targetTrackCount / 2)),
      requestedArtists: resolvedArtists,
    }),
    promptSpec.includeSimilarArtists && resolvedArtists.length > 0
      ? fetchRecommendationTrackCandidates(spotifyApi, resolvedArtists, {
          market: config.spotifyDefaultMarket,
          preferredGenres: promptSpec.genres,
          limit: Math.max(10, promptSpec.targetTrackCount),
        })
      : Promise.resolve([]),
    promptSpec.includeSimilarArtists && resolvedArtists.length > 0
      ? fetchGenreSimilarArtistCandidates(spotifyApi, resolvedArtists, {
          market: config.spotifyDefaultMarket,
          preferredGenres: promptSpec.genres,
          limit: Math.max(6, promptSpec.targetTrackCount / 2),
        })
      : Promise.resolve([]),
  ]);
  const rawCandidates = [
    ...artistCandidates,
    ...recommendationCandidates,
    ...genreFallbackCandidates,
    ...queryCandidates,
  ];
  // For related-pool tracks we apply two safety filters up front so compilation accounts
  // and collab tracks don't pollute the "similar artists" share later.
  const candidates = rawCandidates.filter((candidate) => {
    if (candidate.seedArtistKind !== "related") {
      return true;
    }

    if (!relatedTrackHasRealArtist(candidate)) {
      return false;
    }

    if (
      promptSpec.excludeSimilarArtistCollabsWithRequested &&
      candidate.artistIds.some((artistId) => requestedArtistIds.has(artistId))
    ) {
      return false;
    }

    return true;
  });
  const initialSelection = selectTracks(promptSpec, candidates);
  const reviewedSelection = reviewAndRepairSelection(
    promptSpec,
    initialSelection,
    candidates,
    resolvedArtists,
  );
  // Apply the requested-vs-similar share AFTER review, otherwise reviewAndRepair's
  // re-selection ignores the share composition and falls back to requested-heavy output.
  const shareAdjustedTracks = composeSelectionWithSimilarArtistShare(
    promptSpec,
    candidates,
    reviewedSelection.tracks,
  );
  const selection: typeof reviewedSelection = {
    ...reviewedSelection,
    tracks: shareAdjustedTracks,
    totalDurationMs: totalDurationMs(shareAdjustedTracks),
    diagnostics: {
      ...reviewedSelection.diagnostics,
      selectedTrackCount: shareAdjustedTracks.length,
    },
  };

  if (promptSpec.artists.length > 0 && resolvedArtists.length === 0) {
    throw new Error(
      "The requested artists could not be resolved in Spotify search. Try simplifying the artist names.",
    );
  }

  if (promptSpec.artists.length > 0) {
    const representedArtists = new Set(
      selection.tracks
        .map((track) => track.requestedArtist)
        .filter((artist): artist is string => Boolean(artist)),
    );

    if (representedArtists.size === 0) {
      throw new Error(
        "No tracks from the requested artists could be selected. Try simplifying the prompt or artist list.",
      );
    }
  }

  if (selection.tracks.length === 0) {
    throw new Error(
      "No suitable Spotify tracks were found for this prompt. Try broadening the genres or mood.",
    );
  }

  const playlistName = buildPlaylistName(promptSpec);
  const createdPlaylist = await createPlaylistWithTracks(spotifyApi, {
    name: playlistName,
    description: buildPlaylistDescription(promptSpec),
    isPrivate: promptSpec.isPrivate,
    trackUris: selection.tracks.map((track) => track.uri),
  });

  return {
    promptSpec,
    playlistId: createdPlaylist.id,
    playlistName,
    playlistUrl: createdPlaylist.url,
    queries,
    selectedTracks: selection.tracks,
    totalDurationMs: selection.totalDurationMs,
    diagnostics: selection.diagnostics,
  };
}
