import type { SpotifySkillConfig } from "../config";
import { parsePrompt } from "../domain/parse-prompt";
import { buildSearchQueries, selectTracks } from "../domain/select-tracks";
import { uniqueStrings } from "../domain/filters";
import { createPlaylistWithTracks } from "../spotify/playlists";
import {
  fetchArtistTrackCandidates,
  resolveRequestedArtists,
  searchTrackCandidates,
} from "../spotify/search";
import { getAuthorizedSpotifyClient } from "../spotify/auth";
import type { PlaylistGenerationResult } from "../types";
import type { PromptSpec } from "../domain/prompt-spec";

function toTitleCase(value: string): string {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function buildPlaylistName(spec: PromptSpec): string {
  if (spec.rawPrompt.toLowerCase().includes("playlist called")) {
    return spec.playlistNameHint;
  }

  const leadingTerms = uniqueStrings([...spec.styles, ...spec.activities, ...spec.genres])
    .slice(0, 4)
    .map(toTitleCase);

  if (leadingTerms.length === 0) {
    return "Prompt Playlist";
  }

  return `${leadingTerms.join(" ")} Mix`;
}

function buildPlaylistDescription(spec: PromptSpec): string {
  const cleanTag = spec.allowExplicit ? "explicit-allowed" : "clean-only";
  const artistTag = spec.artists.length > 0 ? ` Artists: ${spec.artists.join(", ")}.` : "";
  const description = `Generated by spotify-playlist-skill (${cleanTag}).${artistTag} Prompt: ${spec.rawPrompt}`;

  return description.slice(0, 300);
}

export async function generatePlaylistFromPrompt(
  prompt: string,
  config: SpotifySkillConfig,
): Promise<PlaylistGenerationResult> {
  const promptSpec = parsePrompt(prompt);
  const queries = buildSearchQueries(promptSpec);
  const spotifyApi = await getAuthorizedSpotifyClient(config);
  const resolvedArtists =
    promptSpec.artists.length > 0
      ? await resolveRequestedArtists(spotifyApi, promptSpec.artists)
      : [];
  const [artistCandidates, queryCandidates] = await Promise.all([
    resolvedArtists.length > 0
      ? fetchArtistTrackCandidates(spotifyApi, resolvedArtists, {
          market: config.spotifyDefaultMarket,
        })
      : Promise.resolve([]),
    searchTrackCandidates(spotifyApi, queries, {
      market: config.spotifyDefaultMarket,
      limitPerQuery: Math.max(10, Math.ceil(promptSpec.targetTrackCount / 2)),
    }),
  ]);
  const candidates = [...artistCandidates, ...queryCandidates];
  const selection = selectTracks(promptSpec, candidates);

  if (promptSpec.artists.length > 0 && resolvedArtists.length === 0) {
    throw new Error(
      "The requested artists could not be resolved in Spotify search. Try simplifying the artist names.",
    );
  }

  if (promptSpec.artists.length > 0) {
    const representedArtists = new Set(
      selection.tracks
        .map((track) => track.requestedArtist)
        .filter((artist): artist is string => Boolean(artist)),
    );

    if (representedArtists.size === 0) {
      throw new Error(
        "No tracks from the requested artists could be selected. Try simplifying the prompt or artist list.",
      );
    }
  }

  if (selection.tracks.length === 0) {
    throw new Error(
      "No suitable Spotify tracks were found for this prompt. Try broadening the genres or mood.",
    );
  }

  const playlistName = buildPlaylistName(promptSpec);
  const createdPlaylist = await createPlaylistWithTracks(spotifyApi, {
    name: playlistName,
    description: buildPlaylistDescription(promptSpec),
    isPrivate: promptSpec.isPrivate,
    trackUris: selection.tracks.map((track) => track.uri),
  });

  return {
    promptSpec,
    playlistId: createdPlaylist.id,
    playlistName,
    playlistUrl: createdPlaylist.url,
    queries,
    selectedTracks: selection.tracks,
    totalDurationMs: selection.totalDurationMs,
    diagnostics: selection.diagnostics,
  };
}
